version: '3.8'

services:
  mysql-db:
    image: mysql:8.0.33
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "Nuvelabs123$"
      MYSQL_DATABASE: tododb
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pNuvelabs123$"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    volumes:
    - mysql-data: /var/lib/mysql
    networks:
    - todo-network
  volumes:
    mysql-data:
      name: mysql-data
  

  todo-application:
    image: todo-application-image:latest
    container_name: todo-application
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tododb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "Nuvelabs123$"
    ports:
      - "8082:8081"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - todo-network
    command: ["./wait-for-it.sh", "mysql-db:3306", "--", "java", "-jar", "app.jar"]

networks:
  todo-network:
    name: todo-network
    driver: bridge
