version: '3.8'
services:
  todo-application:
    image: todo-application-image:latest
    container_name: todo-application
    ports:
      - "8082:8081"
    networks:
      - todo-network
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: tododb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network

volumes:
  mysql-data:

networks:
  todo-network:
    driver: bridge
