apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-application
  template:
    metadata:
      labels:
        app: todo-application
    spec:
      containers:
      - name: todo-application
        image: srikantb1/todo-application:latest
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: my-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: todo-application-service
spec:
  selector:
    app: todo-application
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  type: NodePort
  nodePort: 30080
